### ISSUE TITLE
New post not shown properly

### ISSUE THREAD

**Issue by Nikronic** [iust-projects/iust-projects.github.io#2]
Please see commit https://github.com/iust-projects/iust-projects.github.io/commit/5f4eb281fd698e97e5952ca97277799d5ea411bf

**Comment by avestura** [comment]
I can't see the problem in the commit. What's wrong with the post?

**Comment by avestura** [comment]
Anyways, I think we need "/post/:title" permalink for posts. Also maybe we should attach date time to the post's url? debatable. It can prevent posts with the same ids, but also breaks the link between comment and post if the date changes.

**Comment by Nikronic** [comment]
It is ok now, I think it was because of those DNS stuff problem? IDK.

About the permalink I think it's a good idea but I don't know about date. About the controlling website and its stuff, do whatever you think is right, I have no experience and knowledge as you know!

**Comment by avestura** [comment]
It is always the DNS!

I'll take care of that part, but any feedback is very welcome.

**Comment by Nikronic** [comment]
Also see this 
![image](https://user-images.githubusercontent.com/32401852/73649996-4d0da500-4696-11ea-8995-1e45c6562052.png)

The title in bar is the one from the post you created initially. I created a separate post in `_posts` and created `dip01` folder under assets folder for images, etc. So the titles mismatched.

**Comment by avestura** [comment]
> The title in bar is the one from the post you created initially

Those are links to previous and next posts. In case there is no next post yet, only the previous one is shown.

**Comment by Nikronic** [comment]
>Those are links to previous and next posts. In case there is no next post yet, only the previous one is shown.

Oh I didn't know that! Thanks!
