### ISSUE TITLE
Erfan looks disastrous!

### ISSUE THREAD

**Issue by Nikronic** [iust-projects/iust-projects.github.io#4]
![image](https://user-images.githubusercontent.com/32401852/74139061-f4935600-4c07-11ea-9408-66b1965ad15f.png)

**Comment by avestura** [comment]
I recommend people to use their GitHub account photo, which is in square shape and in jpeg format. Erfan uploaded a wide photo of himself without cropping and in PNG format (takes way longer to load)! 

ping @erfanMhi

**Comment by Nikronic** [comment]
I am reopening this as the image profile is not appropriate yet.

@erfanMhi

**Comment by avestura** [comment]
> I am reopening this as the image profile is not appropriate yet.

fair enough
