### ISSUE TITLE
Regime of using tags for posts

### ISSUE THREAD

**Issue by Nikronic** [iust-projects/iust-projects.github.io#5]
As you guys all are software engineer you know better than me.
Do we need to devise a plan for using `tags` for posts?

Here are some questions pertains this matter:
* Do the tags need be subset or superset words has been used in titles?
* Tags could be topics of posts at all? or just organization terms like 'featured', etc?
* Any other ideas?

Actually, I was going to add `digital image processing`, `cv` and `python` to all my posts and also a few post specific tags too.

**Comment by avestura** [comment]
> As you guys all are software engineer you know better than me.

I guess this is more of a SEO thingy than software thingy. (Which I suck at it)

> Do the tags need be subset or superset words has been used in titles?

I think putting related tags is enough, no matter they are superset or subset.

> Tags could be topics of posts at all? or just organization terms like 'featured', etc?

"featured" tag is a special tag. Those posts are shown in the featured section of the website:

![image](https://user-images.githubusercontent.com/9091958/74143376-f2cd9080-4c0f-11ea-8a27-2e35c475aae9.png)

If you want to put a well-written rich post there, use that tag. I think you removed this from one of your posts that I've added?

> Actually, I was going to add digital image processing, cv and python to all my posts and also a few post specific tags too.

That's cool. Go for it!

**Comment by Nikronic** [comment]
>If you want to put a well-written rich post there, use that tag. I think you removed this from one of your posts that I've added?

Yes, actually I removed the post you created as it was referring to all folders in the repo. Now I am creating a post for each homework (folder).
