### ISSUE TITLE
"Etc" in title of the posts

### ISSUE THREAD

**Issue by avestura** [iust-projects/iust-projects.github.io#6]
@Nikronic I see that you use "etc" in the title of your posts. Do we really need them?
I mean, would that be a big deal to use: "**Face Detection, Face Landmarks and dlib**"
Instead of: "**Face Detection, Face Landmarks, dlib, etc**"

In my opinion, 'etc' is used when I can guess the rest of the sequence, but I'm not sure if I can do that in this case. Also, using the first title style still covers '_and similar things_' in it I believe.

**Comment by Nikronic** [comment]
@0xaryan Yes you right!
For few first posts, I wasn't using tags so some times title got too long that's why I used 'etc' but for other posts I've just copied it to have similar structure. I can remove them, they no longer needed!

**Comment by avestura** [comment]
Nice!
