### ISSUE TITLE
'featured' does not work in combination with other tags

### ISSUE THREAD

**Issue by Nikronic** [iust-projects/iust-projects.github.io#7]
For instance see [post 10](http://iust-projects.ir/post/dip10/)
![image](https://user-images.githubusercontent.com/32401852/74520501-f40efe00-4f2c-11ea-8534-163bc40a2686.png)

http://iust-projects.ir/tags.html#featured
![image](https://user-images.githubusercontent.com/32401852/74520407-bd38e800-4f2c-11ea-9885-8b1157c65dae.png)

**Comment by avestura** [comment]
Please use lowercase 'featured' instead of 'Featured' in your markdown files.

FWIW tags list in the rendered html are automatically shown lowercase.

**Comment by avestura** [comment]
Fixed the tags.

**Comment by Nikronic** [comment]
Thank you!
